### ISSUE TITLE
A bug in the logged_in() method

### ISSUE THREAD

**Issue by Glowieh** [benedmunds/CodeIgniter-Ion-Auth#819] opened 2015-07-29 15:53 UTC
I found a bug in the library function logged_in() while setting up a new CodeIgniter+Ion_auth app with a non-default identity column name.

It's retrieving the user-configured identity column name from session userdata (currently lines 434 and 436 in libraries/Ion_auth.php) while it should be retrieving plain $this->session->userdata('identity'); since the set_session function in the model is saving the relevant data in 'identity', not in the user-configured identity column name (currently line 1744 in models/ion_auth_model.php).

I hope this is a good place to contribute a quick bug report like this one with a fix attached.

**Comment by benedmunds** [comment] 2015-07-29 16:30
Could you send a PR with the fix?

**Comment by Glowieh** [comment] 2015-07-29 17:53
Sure, I just didn't know if it was appropriate with such a small fix. I'll do it in a moment.

**Comment by avenirer** [comment] 2015-07-29 19:09
It's not a bug. In the logged_in() method is retrieving the identity column name from the config in order to retrieve the session data corelated to that identity column. I thouls not be retrieving plain $this->session->userdata('identity') as this would simply allow a user to set anything as identity by just changing the cookies (as per CI version 2.x). The set_session function (method actually) is not saving the relevant data in "identity". In identity is just saving the identity column name.

**Comment by avenirer** [comment] 2015-07-29 19:23
How did you reach the conclusion that this is a bug? Did the library not work correctly?

**Comment by Glowieh** [comment] 2015-07-29 19:41
Yeah, the library didn't work as I expected it to. I'll explain what I did from the start so you can point out where I made the misstep since I'm still confused.

In this new CI+Ion_auth app I'm working on I created a replacement database table for the default users table and added some new fields to it that I'm going to need. Among these is the field pinnumber that I'll be using as the login field and configured it as such in ion_auth's config file.

I started testing whether my non-standard database scheme worked and noticed that yes, I can login successfully, but the logged_in() method is returning false. I started debugging. This new pinnumber field isn't one of the default ion_auth fields obviously, so I noticed that the logged_in() method is trying to find 'pinnumber' from userdata, here:

$identity = $this->config->item('identity', 'ion_auth');
return (bool) $this->session->userdata($identity);

It can't find pinnumber from there, because of this, I concluded:

$session_data = array(
    'identity'             => $user->{$this->identity_column},
    'username'             => $user->username,
    'email'                => $user->email,
    'user_id'              => $user->id, //everyone likes to overwrite id so we'll use user_id
    'old_last_login'       => $user->last_login
);
$this->session->set_userdata($session_data);

Since it's saving the login name to 'identity'. I promptly changed logged_in() to retrieve 'pinnumber' and the method started working as expected, ie. returning whether the user is logged in or not.

Where's my mistake?

**Comment by avenirer** [comment] 2015-07-29 19:49
The thing is that if you did it this way, every user will be seen by the CI as "pinnumber" (literally), and not the pin number which is unique to every user (I hope you understand what I am saying here). You could either rename the column in the database as "username" instead of "pinnumber" (because, in fact the pin number is also a username), or use the triggers (callbacks or whatever they are called).

**Comment by Glowieh** [comment] 2015-07-29 21:24
Opening my thought process further here.

As I see it, logged_in() is only interested whether there's any session data currently saved and deduces from that if the user is logged in or not. It's not interested in the actual data there, right? That's why retrieving plain 'identity' is okay. It's always there if you're logged in.

In your first post you said: "It should not stop at only retrieving plain $this->session->userdata('identity') as this would simply return the value of "identity", which can only be "username" or "email"."

Actually it's retrieving the login name there, not just the identity column name (like "username" or "email"). If I'm logged in as pin 12345, it retrieves that and deduces that yeah, there's userdata there so I'm logged in and returns true.

You also said: "The set_session function (method actually) is not saving the relevant data in "identity". In identity is just saving the identity column name."

If I'm reading this right, I'd say this is wrong. This is what it's saving in 'identity': 
'identity' => $user->{$this->identity_column},
Note the curly braces; it saves the login name, not the column name, no? Same as 'identity' => $user->pinnumber for me.

In the previous post you said: "The thing is that if you did it this way, every user will be seen by the CI as "pinnumber" (literally), and not the pin number which is unique to every user (I hope you understand what I am saying here)."

Either I'm not understanding what you're saying or it's about the same thing as those previous quotes where I'm disagreeing with you.

I can't easily rename pinnumber in the database because this is a new version of an existing system that uses pinnumber in numerous places in its database scheme as a foreign key. I could just go with username for ion_auth and duplicate the data field as pinnumber for those existing needs, but I'd rather try to eliminate duplication of data like that. That's beyond the point of this bug report though, the validity of the bug report isn't tied to my project.

(Thanks for this peer reviewing, I appreciate someone checking my perhaps hasty conclusions.)

**Comment by benedmunds** [comment] 2015-07-29 22:48
So I believe that @Glowieh is correct here after further review.  This change would indeed pull the data from the identity and fixes the bug that was found.  

Make sense @avenirer ?

**Comment by avenirer** [comment] 2015-07-30 07:01
Yes @Glowieh, after further looking, you are right. I have been to hasty with the conclusions (especially the one related to the set_session in the model).

**Comment by benedmunds** [comment] 2015-07-31 17:24
Merged!  Thanks @Glowieh

**Closed by benedmunds** 2015-07-31 17:24 UTC
