### ISSUE TITLE
Deactivate dependes on not-imported library

### ISSUE THREAD

**Issue by phalox** [benedmunds/CodeIgniter-Ion-Auth#1263] opened 2018-08-19 17:18 UTC
It seems that the deactivate function in the model is the only one that relies back on the library code... But in the model, the library is not included, therefore it throws an error

https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/models/Ion_auth_model.php#L449

Adding at the start of the method, fixes the issue:
`$this->load->library('ion_auth');`

**Comment by benedmunds** [comment] 2018-08-19 18:57
Can you post an example of your code? Are you calling the model directly or via the library?

**Comment by phalox** [comment] 2018-08-19 19:04
Sure! This is code from my User controller. So, I'm going via the library, but there it's going straight to the '__call' function. So in a way, you're always straight calling the model.

```
				$user_id = $this->ion_auth->create_user($this->input->post('email'),
												$this->input->post('password'),
												$this->input->post('email'),
												$additional_data,
												[$this->input->post('group')]
												);
														
				if($user_id)
				{
					$user_added = $this->input->post('email');

					if(!(bool)$this->input->post('active'))
					{
						$deactivate = $this->ion_auth->deactivate($user_id);
					}
				}
```

**Comment by benedmunds** [comment] 2018-08-19 19:08
Seems odd that it’s not already in the CI super global there.  Are you autoloading the model by chance? Note, that it shouldn’t be.

If not, what CI version? I’ll attempt to reproduce and do a hotfix.

**Comment by phalox** [comment] 2018-08-19 20:07
I did some further testing here, and it seems it's due to my little hack (now you probably think, well duuuuh) :-).

I've subclassed the library as MyAuth, to make some level of abstraction, and to be able to add features I need myself. It might be that due to the passthrough (library -> model), this does not always work. But I didn't figure out the cause yet.

Conclusion: Standard setup seems to work! If you make a subclass for the library, and then try to run certain calls (create_user for example), you need to do some modifications.

**Comment by benedmunds** [comment] 2018-08-19 21:15
Ok awesome, thanks for the update!

**Comment by phalox** [comment] 2018-10-17 05:57
I'm back! With the changes in the library, I really need to make sure that all library code stays clean: no modifications!

To be able to change libraries more easily (this is the 3rd user lib i'm using due to lack of support or just a bad API), I wanted to add a layer in between: MyAuth.

To not have to redefine every single function, I've simply subclassed Ion_Auth (which is probably not 100% clean, but it's the fastest).

Would you have any idea why creating a subclass is breaking the auto load of the model?? Maybe I can make a modification in my own code.

Here's my modification:
`	/**
	 * Updates a users row with an activation code.
	 *
	 * @param int|string|null $id
	 *
	 * @return bool
	 * @author Mathew
	 */
	public function deactivate($id = NULL)
	{
		// WARNING MODIFICATION we need this because the sublcass breaks the auto load
		$this->load->library('ion_auth');`

Thanks for your support!

**Comment by benedmunds** [comment] 2018-10-17 13:39
It's because the files that are loading via Ion Auth are "namespaced" to ion_auth when loading them.  I put namespace in quotes cause it's not a true namespace, but is the way CI lets you group items that you load.

If you're extending the Ion Auth library this should still work I believe.

**Comment by phalox** [comment] 2018-10-17 16:08
For some reason it doesn't work...

`
class MyAuth extends Ion_auth
{

	public function __construct()
	{
		parent::__construct();
	}
...
`

Could it be because the deactivate() function is calling ion_auth->logged_in() and not myauth->logged_in()? Therefore the subclassed library isn't auto loaded?

`
	public function deactivate($id = NULL)
	{
		// WARNING MODIFICATION we need this because the sublcass breaks the auto load
		$this->load->library('ion_auth');
		$this->trigger_events('deactivate');

		if (!isset($id))
		{
			$this->set_error('deactivate_unsuccessful');
			return FALSE;
		}
		else if ($this->ion_auth->logged_in() && $this->user()->row()->id == $id)
		{
			$this->set_error('deactivate_current_user_unsuccessful');
			return FALSE;
		}
...
`

**Comment by benedmunds** [comment] 2018-10-18 13:19
Are you getting an error just with deactivating? Or what’s happening exactly?

**Comment by phalox** [comment] 2018-10-19 07:29
Hi Ben,

Indeed. the deactivate() function is the only one that relies back on the
library functions (from the model). So it seems that indeed a subclass
(MyAuth) of IonAuth causes an incorrect autoload of the IonAuth library (or
is it autoloading the MyAuth library and therefore failing the call?) (can
I see the loaded libraries?)

**Comment by benedmunds** [comment] 2018-10-19 12:34
Gotcha.  You have any thoughts on how to best handle this?  Maybe injecting the library in to the model on load?

**Comment by benedmunds** [comment] 2018-11-28 16:34
Closing due to age, will reopen when/if we revisit this.

**Closed as completed by benedmunds** 2018-11-28 16:34 UTC
