### ISSUE TITLE
codeigniter session problem cloudflare

### ISSUE THREAD

**Issue by xaiborweb** [benedmunds/CodeIgniter-Ion-Auth#1299] opened 2018-12-15 17:21 UTC
Hi, I'm using Ion Auth social
https://github.com/ghosthouse/CodeIgniter-Ion-Auth-Social
and throughout my web check if the user has a session started or not.
```
if ($ this-> ion_auth-> logged_in ()) {
}
```
For this reason in /application/config/autoload.php charge
`$ autoload ['libraries'] = array ('ion_auth');`
in my localhost everything is perfect, but in my website protected with cloudflare, create multiple sessions just with this:
`__ci_last_regenerate | i: 1544893031;`
creates more than 50 sessions per second with just this info which overloads my sql, obviously it is a problem of codeigniter sessions with cloudflare, I have already created the request in the codeigniter github but it does not seem to matter to them.

So I'm wondering if you can share an option / solution, so that only one codeigniter session is created when the user logs in Ion Auth.

Thank you.

**Comment by benedmunds** [comment] 2018-12-15 17:51
Hey, I’ve never seen this before. Probably worth following up on the CI forums and/or stackoverflow.

**Comment by benedmunds** [comment] 2019-02-20 22:46
Closing.  

@xaiborweb feel free to comment and tag me if you have more info or a reason to believe this is Ion Auth specific.  If you've solved this I'd definitely appreciate details for anyone that has this problem in the future.  Thanks!

**Closed as completed by benedmunds** 2019-02-20 22:46 UTC

**Comment by gorkijatt** [comment] 2023-12-05 22:21
i am having the same issue.. i am alo using cloudflare.. had your problem solved ? may be the problem is with running ci3 on latest php versions like 8
