### ISSUE TITLE
Problem with logon after upgrade to CodeIgniter 3.0 RC

### ISSUE THREAD

**Issue by tikky** [benedmunds/CodeIgniter-Ion-Auth#719] opened 2015-01-28 13:37 UTC
Hello,

I've just updated my application to Code Igniter 3.0 RC, and logginig did not work.
I can see a login panel, however is not possible to log on.

After investigation I've found that one particular CodeIgniter file seems to make a problem.
The file is located in:
CodeIgniter-3.0rc\system\libraries\Session\Session.php
Or you can access directly from CI repository:
https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Session/Session.php

Are you able to check the compatibility with the newest version of CodeIgniter?

I will appreciate your help.

**Comment by benedmunds** [comment] 2015-01-29 18:21
Yes it should be fine.  What error are you seeing?  


-Ben Edmunds
 ben.edmunds@gmail.com

**Comment by avenirer** [comment] 2015-01-30 13:09
There is no Session.php inside system/libraries/Session in CodeIgniter 3. Now the Session is a driver, not a library. Maybe the problem is with your application and not with the Ion_Auth

**Comment by tikky** [comment] 2015-01-30 13:25
I do not have any error message - after clicking to logon I can still see the same login form.

Avenirer: what you mean is no Session.php file?
Take a look at my link to CodeIgniter repository:
https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Session/Session.php

**Comment by avenirer** [comment] 2015-01-30 13:34
What you see in that link is a file that is for CI 2.2, and not for CI 3. When you updated your application from 2.x to 3, you didn't update correctly. You should follow these steps http://www.codeigniter.com/userguide3/installation/upgrade_300.html . Pay special attention to how the session works in CI 3.

**Comment by tikky** [comment] 2015-01-30 15:01
Hello again. I disagree.

First - I've started to develop my app few months ago in CI dev version (aka 3.0), and now I've upgraded to 3.0 RC. So I do not need to follow steps 2.x -> 3

Second, the mentioned file Session.php still exists in 3.0.

Take a look at this post forum, which announce 3.0 RC:
http://forum.codeigniter.com/thread-890.html

You can download newset version from here:
https://github.com/bcit-ci/CodeIgniter/archive/3.0rc.zip
...and you will still find Session.php

**Comment by cristiangile** [comment] 2015-01-30 16:08
There was a session bug in CI3 fixed yesterday: 

https://github.com/bcit-ci/CodeIgniter/commit/00c222db1e23ecc3692a5ca5664d8fc25f1789fc

**Comment by tikky** [comment] 2015-01-31 11:41
Hello again,

I have tried to downlad latest CodeIgniter, but sill Session.php seem to ba an issue.
When I've copied back only this one file (session.php) from backup, I can back login without a trouble.

**Comment by benedmunds** [comment] 2015-02-01 21:30
Might want to move this discussion to the CI repo if it's a bug in CI.  Closing since it's not Ion Auth specific but feel free to continue discussing here as well.

**Closed by benedmunds** 2015-02-01 21:30 UTC
