### ISSUE TITLE
Ion Auth 3: help needed for testing

### ISSUE THREAD

**Issue by Indigo744** [benedmunds/CodeIgniter-Ion-Auth#1220] opened 2018-03-26 19:38 UTC
Dear all,

I've worked with @benedmunds  to bring you **Ion Auth 3** (available in [the new `3` branch ](https://github.com/benedmunds/CodeIgniter-Ion-Auth/tree/3)), which brings the latest security improvements from PHP.

The complete [changelog](https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/CHANGELOG.md) is as follow:

>  - **New server requirements:**
>     - Drop CodeIgniter 2 support
>     - Drop PHP < 5.6 support
>  - **Updated password hashing methods:**
>     - Drop SHA1 support (but support seamless migration from SHA1-based installation)
>     - Drop internal Bcrypt library (now uses built-in PHP functions)
>     - Add argon2 support (PHP > 7.2)
>     - Implements password automatic rehashing on login if needed (e.g. when hashing parameters changed)
>  - **Updated config values:**
>     - Higher default hashing parameters (e.g. higher cost for bcrypt)
>     - Allows different hashing parameters for admins
>     - Remove `random_rounds` bcrypt feature
>     - Better default value for `forgot_password_expiration`
>  - **Updated features:**
>      - Update _Remember me_ feature for more security
>      - Update _Password Reset_ feature for more security
>      - Update _User activation_ feature for more security
>  - **Removed features:**
>     - Remove `forgotten_password_complete` feature

Before publishing, we need of course to test it. While we have done some testing on our side, we can't reproduce all the various environments. Hence this little _call for help_.

You will find an [UPGRADING.md](https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/UPGRADING.md) file to help you migrating from 2 to 3.

Thanks a lot. Should you find any issue, feel free to report it here.

**Comment by benedmunds** [comment] 2018-03-26 19:43
@avenirer @lloricode can you review this as well please

**Comment by lloricode** [comment] 2018-03-27 12:18
hmm @benedmunds can we create a unit test with this?

**Comment by Indigo744** [comment] 2018-03-27 12:22
That would be a really great improvements! But I fear I would not have the time right now 😞 if anyone would like to take it from here and implements Unit testing, that would surely be great.

By the way, I've heard CI4 will come with a full-fledged Unit Testing library. Will it be possible to use it for library?

**Comment by lloricode** [comment] 2018-03-27 12:26
@Indigo744 , the problem is, we need to reseach how to properly add some unit test for CI libraries,
we need a test project structure of CI, to run the test,

then a CI4? but still now ready for production, so we cant assure

**Comment by lloricode** [comment] 2018-03-27 12:29
i think this would help 
https://github.com/kenjis/ci-phpunit-test

**Comment by lloricode** [comment] 2018-03-27 12:30
i try to implement this, but we need to add some file of repo, then give instruction what will be need to copy to their projects

**Comment by Indigo744** [comment] 2018-03-27 12:31
That looks good indeed. I'm in favor of putting everything in a `test` sub-directory so user will know they can ignore this directory for production.

**Comment by lloricode** [comment] 2018-03-27 12:32
@Indigo744  then we need to add travis CI Integration for every pull request of this repo,
@avenirer @benedmunds what do you think?

**Comment by lloricode** [comment] 2018-03-27 12:33
https://travis-ci.org/

**Comment by Indigo744** [comment] 2018-03-27 12:33
When the UT will be up and running, we will be able to add CI easily. But that's not the hardest part IMO 😅 ...

**Comment by benedmunds** [comment] 2018-03-27 12:38
@lloricode go for it if you can!

I'm not sure how that'll go with this CI3 version but we can definitely do it for the CI4 version, would be great if you get it working well with CI3 though!

**Comment by benedmunds** [comment] 2018-03-27 12:38
and I'd recommend a /test directory as well

**Comment by lloricode** [comment] 2018-03-27 12:39
:) hmm, it will takes time for this, then almost a year when last I using codeigniter :D but im willing to do reaserch on how it will work :)

**Comment by lloricode** [comment] 2018-03-27 12:40
@benedmunds yes, it mandatory :)

**Comment by lloricode** [comment] 2018-03-27 12:49
@benedmunds  branch `3` is need to test? so we can create a branch pull form branch 3?

**Comment by benedmunds** [comment] 2018-03-27 12:51
@lloricode yea you can submit PRs against the 3 branch

**Comment by lloricode** [comment] 2018-03-27 12:53
@benedmunds thanks :)

**Comment by lloricode** [comment] 2018-04-14 18:11
hi! i just starting the test structure, so maybe later can implement a unit and feature test

ive just temporary made the test here,
https://github.com/lloricode/codeigiter-ion-auth-unit-test
 because so many changes, but same code on ion auth branch 3, 

my plan is, in every automated test, it first pull then latest code from this ion auth branch 3

**Comment by benedmunds** [comment] 2018-04-14 18:13
I’m cool with merging the units tests directly to core once they’re ready, if that works for you. So I wouldn’t spend any time trying to automate pulling the latest code.

**Comment by lloricode** [comment] 2018-04-14 18:16
yes after done this, i will made the PR, if you satisfy also the test implementing

**Comment by benedmunds** [comment] 2018-04-14 18:16
Ok awesome, thanks!

**Comment by lloricode** [comment] 2018-04-14 18:16
Most welcome @benedmunds

**Comment by bvrignaud** [comment] 2018-06-01 15:45
Hi,

I'm trying the new Ion Auth 3 and everything looks like OK. Good Job.

When do you thinks we can start a CI 4 branch ?

**Comment by enlivenapp** [comment] 2018-06-29 18:53
I'm using Ion Auth 3 (dev currently) integrated in a REST API.

Argon2, 
PHP 7.2, 
CI 3.1.9,
https://github.com/chriskacerguis/codeigniter-restserver/releases/tag/3.0.3

 It's working well so far and quite fast on my slow dev box.

**Comment by marios88** [comment] 2018-08-06 11:55
Upgraded and everything works fine!

Are there any plans to implement OTP in version 3?

**Comment by phalox** [comment] 2018-08-12 10:34
Migrating my CI2 with flexi auth to ion auth (v3 the dev branch).. so far so good :)

Been a while that I did PHP dev, now I understand bcrypt also handles the salting which is a nice touch!

1 question though: is there somewhere updated docs? I believe the docs folder in the 3 branch isn't up to date...

**Comment by phalox** [comment] 2018-08-19 17:05
Hi devs!

I'm trying out a slightly specific registration flow as follows:
1. admin invites user on email address. I'm disabling the account and will send an email with the activation_code
2. user goes to activation_code url, where he has to enter all his personal details

I see in the config that "email_activation" exists, but it does nto seem to be used anywhere. is this still in development? So far the library is working pretty good. Only this activation stuff is a bit strange.

**Comment by benedmunds** [comment] 2018-10-24 14:47
@phalox hey, it's used here now:
https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/libraries/Ion_auth.php#L240

**Comment by simmonspaul** [comment] 2018-11-13 22:05
Straight forward upgrade from Auth 2 - thanks for that.
Everything looks seamless and is working. 

I will get my gorillas out in...

**Comment by benedmunds** [comment] 2018-11-28 16:21
Going to go ahead and bump the 3 branch to be the default.  Closing this ticket, any new issue can go into the general issues stream.

**Closed as completed by benedmunds** 2018-11-28 16:21 UTC

**Comment by Indigo744** [comment] 2018-11-28 16:39
Good move @benedmunds 
I have been using v3 since the beginning without an issue. Glad to see this version come to light! 😸
